version: '3.7'

services:
    db:
        image: mysql:5.7
        container_name: mysql_c1
        restart: always
        volumes:
            - mysqldata:/var/lib/mysql
            - ./articles.sql:/docker-entrypoint-initdb.d/articles.sql
        environment:
            MYSQL_ROOT_PASSWORD: test
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    frontend:
        image: myapp
        container_name: myapp_c1
        restart: always
        volumes:
            - ./app:/var/www/html
        ports:
            - 8070:80
        depends_on:
            - db

volumes:
  mysqldata:
networks:
   mynet1:
